plugins {
    id 'java'
    id 'application'
}

group = 'it.unicam.cs.mpgc.rpg123465'
version = '0.1.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'it.unicam.cs.mpgc.rpg123465.MainApp'
}

test {
    useJUnitPlatform()
}